services:
  auth-db:
    build:
      context: ./auth-db
      dockerfile: Dockerfile
    container_name: auth-db
    restart: always
    environment:
      - POSTGRES_USER: ${AUTH_DB_USER}
      - POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      - POSTGRES_DB: ${AUTH_DB_NAME}
    ports:
      - "${AUTH_DB_PORT}:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
      - ./config/init_auth.sql:/docker-entrypoint-initdb.d/init.sql  
    networks:
      - delta_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_DB_USER} -d ${AUTH_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  auth-service:
    build: ./auth-service
    ports:
      - "3001:3000"
    environment:
      - RUST_LOG=info
      - APP_ENVIRONMENT=${APP_ENVIRONMENT:-development}
      - APP_DATABASE__HOST=db
      - APP_DATABASE__USER=${DB_USER:-postgres}
      - APP_DATABASE__PASSWORD=${DB_PASSWORD:-postgres}
      - APP_DATABASE__NAME=${DB_NAME:-auth_service}
    volumes:
      - ./auth-service/config:/usr/local/bin/config  
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - delta_network

volumes:
  auth_db_data:

networks:
  delta_network:
    driver: bridge