services:
  auth-db:
    build:
      context: ./source/auth-db
      dockerfile: Dockerfile
    image: delta/auth-db:latest
    container_name: auth-db
    ports:
      - "${AUTH_DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_NAME}
    volumes:
      - auth_db_data:/var/lib/postgresql/data
      - ./config/auth_db_init.sql:/docker-entrypoint-initdb.d/init.sql  
    networks:
      - delta_network

  auth-service:
    build:
      context: ./source/auth-service
      dockerfile: Dockerfile
    image: beta/auth-service:latest
    container_name: auth-service
    ports:
      - "3000:3000"
    volumes:
      - ./.env:/app/.env 
    working_dir: /app
    environment:
      - RUST_LOG=info
    networks:
      - delta_network  

volumes:
  auth_db_data:

networks:
  delta_network: