[package]
name = "back-service"
version = "0.1.0"
edition = "2024"

[dependencies]
deadpool-postgres = "0.14.1"
tokio-postgres = { version = "0.7.14", features = ["with-chrono-0_4", "with-uuid-1"] }
dotenvy = "0.15.7"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
serde = { version = "1.0.227", features = ["derive"] }
serde_json = "1.0.145"
actix-web = "4.11.0"
thiserror = "2.0.17"
tokio = { version = "1.47.1", features = ["full"] }

