// app/countries.rs

use actix_web::{HttpResponse, Responder, web};
use serde::{Deserialize, Serialize};
use tracing::info;

use crate::domain::countries::{Country, CountryService}; // Access your domain types (Country struct, CountryService)
use crate::errors::AppError; // Access your central AppError
use sqlx::PgPool; // For the db_test_handler, if you keep it here

// --- DTOs (Data Transfer Objects) ---

/// DTO for creating a new Country.
/// 'id' and 'created_at' are omitted as they're generated by the database/service.
#[derive(Debug, Deserialize)]
pub struct CreateCountryDto {
    pub name: String,
    pub code: String,
    pub created_by: Option<String>,
}

/// DTO for updating an existing Country.
/// All fields are optional as only some might be updated.
#[derive(Debug, Deserialize)]
pub struct UpdateCountryDto {
    pub name: Option<String>,
    pub code: Option<String>,
    // updated_by will be passed separately from the handler, e.g., from auth context
}

// --- Handlers ---

// These two handlers are general and might eventually move elsewhere,
// but for consolidation, we'll keep them here for now.

/// GET /hello - A simple "hello world" handler.
pub async fn hello_world_handler() -> impl Responder {
    info!("Received request for /hello.");
    HttpResponse::Ok().body("Hello, World!")
}

/// GET /db_test - Handler to test database connection.
pub async fn db_test_handler(db_pool: web::Data<PgPool>) -> Result<HttpResponse, AppError> {
    info!("Received request for /db_test.");
    // This query is for testing the connection. `sqlx::query!` needs `cargo sqlx prepare`
    // to have been run successfully.
    sqlx::query("SELECT 1").execute(db_pool.get_ref()).await?;
    info!("Database ping successful from handler.");
    Ok(HttpResponse::Ok().body("Database connection test successful!"))
}

/// GET /countries - List all countries.
/// This handler fetches all countries using the CountryService and returns them as JSON.
pub async fn list_countries_handler(
    country_service: web::Data<CountryService>,
) -> Result<HttpResponse, AppError> {
    info!("Received request to list all countries.");
    let countries = country_service.get_all_countries().await?;
    // The Country struct must implement `Serialize` (which it does) for this to work.
    Ok(HttpResponse::Ok().json(countries))
}

/// GET /countries/{id} - Get a single country by ID.
/// This handler extracts the ID from the path, fetches the country, and returns it as JSON.
/// Returns 404 if the country is not found.
pub async fn get_country_by_id_handler(
    country_service: web::Data<CountryService>,
    path: web::Path<i32>, // Actix Web extracts the {id} path parameter as an i32
) -> Result<HttpResponse, AppError> {
    let id = path.into_inner(); // Get the i32 value from Path
    info!("Received request for country with ID: {}.", id);
    let country = country_service.get_country_by_id(id).await?;

    match country {
        Some(c) => Ok(HttpResponse::Ok().json(c)), // Return 200 OK with JSON
        None => {
            info!("Country with ID: {} not found.", id);
            // Return an AppError which will be converted to a 500 or 404 by ResponseError trait
            Err(AppError::ServiceError(format!(
                "Country with ID {} not found.",
                id
            )))
        }
    }
}

/// POST /countries - Create a new country.
/// This handler deserializes a JSON request body into `CreateCountryDto`,
/// uses the CountryService to create the country, and returns the newly created country as JSON.
pub async fn create_country_handler(
    country_service: web::Data<CountryService>,
    json_data: web::Json<CreateCountryDto>, // Actix Web deserializes the JSON body
) -> Result<HttpResponse, AppError> {
    info!("Received request to create a country: {:?}", json_data);

    // In a real application, 'created_by' might come from an authenticated user context (e.g., JWT)
    // For now, it's directly from the DTO.
    let created_country = country_service
        .create_country(
            json_data.name.clone(),
            json_data.code.clone(),
            json_data.created_by.clone(),
        )
        .await?;

    // Return 201 Created status with the newly created country object
    Ok(HttpResponse::Created().json(created_country))
}

/// PUT /countries/{id} - Update an existing country.
/// This handler extracts the ID, deserializes a JSON body for updates,
/// and uses the CountryService to perform the update.
pub async fn update_country_handler(
    country_service: web::Data<CountryService>,
    path: web::Path<i32>,                   // Extract ID from path
    json_data: web::Json<UpdateCountryDto>, // JSON body for updates
) -> Result<HttpResponse, AppError> {
    let id = path.into_inner();
    info!(
        "Received request to update country ID {}: {:?}",
        id, json_data
    );

    // In a real application, 'updated_by' would come from an authenticated user context
    let updated_by = "system".to_string(); // Placeholder for actual user

    let updated_country = country_service
        .update_country(
            id,
            json_data.name.clone(),
            json_data.code.clone(),
            updated_by,
        )
        .await?;

    // Return 200 OK with the updated country object
    Ok(HttpResponse::Ok().json(updated_country))
}

/// DELETE /countries/{id} - Delete a country.
/// This handler extracts the ID from the path and uses the CountryService to delete the country.
/// Returns 204 No Content on successful deletion.
pub async fn delete_country_handler(
    country_service: web::Data<CountryService>,
    path: web::Path<i32>, // Extract ID from path
) -> Result<HttpResponse, AppError> {
    let id = path.into_inner();
    info!("Received request to delete country with ID: {}.", id);

    country_service.delete_country(id).await?;

    // 204 No Content is standard for successful DELETE operations that don't return a body.
    Ok(HttpResponse::NoContent().finish())
}

// --- Route Configuration ---

/// Configures all application routes for the `App` instance.
/// This function is intended to be called by `App::new().configure()`.
/// It registers the `/hello`, `/db_test`, and all `/countries` API endpoints.
pub fn configure_routes(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::resource("/hello").to(hello_world_handler), // Maps GET /hello to hello_world_handler
    )
    .service(
        web::resource("/db_test").to(db_test_handler), // Maps GET /db_test to db_test_handler
    )
    .service(
        web::scope("/countries") // Creates a scope for all /countries related routes
            .service(
                web::resource("") // Matches requests to /countries (base path)
                    .route(web::get().to(list_countries_handler)) // GET /countries
                    .route(web::post().to(create_country_handler)), // POST /countries
            )
            .service(
                web::resource("/{id}") // Matches requests to /countries/{id}
                    .route(web::get().to(get_country_by_id_handler)) // GET /countries/{id}
                    .route(web::put().to(update_country_handler)) // PUT /countries/{id}
                    .route(web::delete().to(delete_country_handler)), // DELETE /countries/{id}
            ),
    );
}
