# Parser for mobile subscriber survey result file

# Header
HEADER = { "ORDERED" ~ "\n" ~ "ACT" ~ whitespace+ ~ "MSCBC2" ~ whitespace+ ~ "AD-" ~ digits ~ whitespace+ ~ "TIME" ~ whitespace+ ~ digits ~ whitespace+ ~ "CLUSTER" }

# Body
BODY = { (record ~ "\n")* }

record = {
    hlraddr ~ whitespace+ ~ nsub ~ whitespace+ ~ nsuba
}

hlraddr = { "4-" ~ digits }
nsub = { digits }
nsuba = { digits }

# Footer
FOOTER = {
    "TOTNSUB" ~ whitespace+ ~ digits ~ "\n" ~
    "TOTNSUBA" ~ whitespace+ ~ digits ~ "\n" ~
    "NSUBPR" ~ whitespace+ ~ digits ~ "\n" ~
    "NSUBXP" ~ whitespace+ ~ digits ~ "\n" ~
    "NSUBPXOU" ~ whitespace+ ~ digits ~ "\n" ~
    "NSUBSGS" ~ whitespace+ ~ digits ~ "\n" ~
    "NSUBGS" ~ whitespace+ ~ digits ~ "\n" ~
    "END"
}

# Whitespace
whitespace = { " " | "\t" }

# Digits
digits = { '0'..'9'+ }